language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
env:
    - DEPENDENCIES='django>=1.3,<1.4'
    - DEPENDENCIES='django>=1.4,<1.5'
    - DEPENDENCIES='django>=1.5,<1.6'
    - DEPENDENCIES='django>=1.6,<1.7'
    - DEPENDENCIES='django>=1.7,<1.8'
    - DEPENDENCIES='django>=1.8,<1.9'
    - DEPENDENCIES='django'
install:
    - pip install $DEPENDENCIES 
script:
    python runtests.py
matrix:
  exclude:
    - python: 2.6
      env: DEPENDENCIES='django>=1.7,<1.8'
    - python: 2.6
      env: DEPENDENCIES='django'
    - python: 3.3
      env: DEPENDENCIES='django>=1.3,<1.4'
    - python: 3.3
      env: DEPENDENCIES='django>=1.4,<1.5'
    - python: 3.4
      env: DEPENDENCIES='django>=1.3,<1.4'
    - python: 3.4
      env: DEPENDENCIES='django>=1.4,<1.5'
